grocerylist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('items/', views.items_index, name='index'),
    path('items/<int:item_id>/', views.items_detail, name='detail'),
    path('items/create/', views.ItemCreate.as_view(), name='item_create'),
    path('items/<int:pk>/update/', views.ItemUpdate.as_view(), name='items_update'),
    path('items/<int:pk>/delete/', views.ItemDelete.as_view(), name='items_delete'),
    path('items/<int:item_id>/add_purchase/', views.add_purchase, name='add_purchase'),
    path('stores/', views.StoreList.as_view(), name='stores_index'),
    path('stores/<int:pk>/', views.StoreDetail.as_view(), name='stores_details'),
    path('stores/create/', views.StoreCreate.as_view(), name='stores_create'),
    path('stores/<int:pk>/update/', views.StoreUpdate.as_view(), name='stores_update'),
    path('stores/<int:pk>/delete/', views.StoreDelete.as_view(), name='stores_delete'),
    path('items/<int:item_id>/assoc_store/<int:store_id>/', views.assoc_store, name='assoc_store'),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Store(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('stores_details', kwargs={'pk': self.id})

class Item(models.Model):
    name = models.CharField(max_length=100)
    cost = models.IntegerField()
    quantity = models.IntegerField()
    stores = models.ManyToManyField(Store)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'item_id': self.id})

class Purchase(models.Model):
    date = models.DateField('Purchase date')
    quantity = models.IntegerField()

    item = models.ForeignKey(Item, on_delete=models.CASCADE)

    def __str__(self):
        return self.date

    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Purchase

class PurchaseForm(ModelForm):
    class Meta:
        model = Purchase
        fields = ['date', 'quantity']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Item, Store
from .forms import PurchaseForm

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def items_index(request):
    items = Item.objects.filter(user=request.user)
    return render(request, 'items/index.html', { 'items': items })

@login_required
def items_detail(request, item_id):
    item = Item.objects.get(id=item_id)
    stores_item_doesnt_have = Store.objects.exclude(id__in= item.stores.all().values_list('id'))
    purchase_form = PurchaseForm()
    return render(request, 'items/detail.html', { 'item': item, 'purchase_form': purchase_form, 'stores': stores_item_doesnt_have })

@login_required
def add_purchase(request, item_id):
    form = PurchaseForm(request.POST)
    if form.is_valid():
        new_purchase = form.save(commit=False)
        new_purchase.item_id = item_id
        new_purchase.save()
    return redirect('detail', item_id=item_id)

class ItemCreate(CreateView):
    model = Item
    fields = ['name', 'cost', 'quantity']

    def form_valid(self, form):
      form.instance.user = self.request.user
      return super().form_valid(form)

class ItemUpdate(LoginRequiredMixin, UpdateView):
    model = Item
    fields = ['cost', 'quantity']

class ItemDelete(LoginRequiredMixin, DeleteView):
    model = Item
    success_url = '/items/'

class StoreList(LoginRequiredMixin, ListView):
  model = Store

class StoreDetail(LoginRequiredMixin, DetailView):
  model = Store

class StoreCreate(LoginRequiredMixin, CreateView):
  model = Store
  fields = '__all__'

class StoreUpdate(LoginRequiredMixin, UpdateView):
  model = Store
  fields = ['name', 'location']

class StoreDelete(LoginRequiredMixin, DeleteView):
  model = Store
  success_url = '/stores/'

def assoc_store(request, item_id, store_id):
    Item.objects.get(id=item_id).stores.add(store_id)
    return redirect('detail', item_id=item_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>Grocery List</h1>
<hr />
<p>This is the Grocery List!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Grocery List</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>


</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper green">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;Grocery List&nbsp;</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'stores_create' %}">Add a Store</a></li>
          <li><a href="{% url 'stores_index' %}">View All Stores</a></li>
          <li><a href="{% url 'item_create' %}">Add an Item</a></li>
          <li><a href="{% url 'index' %}">View Groceries</a></li>
          <li><a href="{% url 'logout' %}">Log Out</a></li>
          {% else %}
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
          <li><a href="{% url 'login' %}">Log In</a></li>
          {% endif %}

        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer green">
    <div class="right">All Rights Reserved, &copy; 2021 Erin Doman &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>Home</h1>
{% endblock %}

main_app/templates/items/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Item Details</h1>

<div class="card">
  <div class="card-content">
    <span class="card-title">{{ item.name }}</span>
    <p>Cost: {{ item.cost }}</p>
    <p>Quantity: {{ item.quantity }}</p>
  </div>
  <div class="card-action">
    <a href="{% url 'items_update' item.id %}">Edit</a>
    <a href="{% url 'items_delete' item.id %}">Delete</a>
  </div>
</div>

<div class="card-content">
  <div class="col s6">
    <form action="{% url 'add_purchase' item.id %}" method="post">
      {% csrf_token %}
      {{ purchase_form.as_p }}
      <input type="submit" class="btn" value="Add Purchase">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Quantity</th></tr>
      </thead>
      <tbody>
        {% for purchase in item.purchase_set.all %}
          <tr>
            <td>{{purchase.date}}</td>
            <td>{{purchase.quantity}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

  <hr>
  <div class="row">
    <div class="col s6">
      <h3>{{ item.name }} is available at:</h3>
      {% if item.stores.count %}
        {% for store in item.stores.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                {{ store.name }} in {{ store.location }}
              </span>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>{{ item.name }} is not available at any stores.</h5>
      {% endif %}
    </div>
    <div class="col s6">
      <h3>Available Stores</h3>
      {% if stores.count %}
        {% for store in stores.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                {{ store.name }} in {{ store.location }}
              </span>
            </div>
            <div class="card-action">
              <form action="{% url 'assoc_store' item.id store.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn">Add</button>
              </form>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>{{item.name}} can be found in stores everywhere!</h5>
      {% endif %}
    </div>
  </div>


<script>
var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
</script>

{% endblock %}

main_app/templates/items/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Grocery List</h1>

{% for item in items %}
  <div class="card">
    <a href="{% url 'detail' item.id %}">
    <div class="card-content">
      <span class="card-title">{{ item.name }}</span>
    </div>
    </a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/main_app/item_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

    <h1>Delete Item</h1>
    <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span> off your grocery list?</h4>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes" class="btn">
        <a href="{% url 'detail' item.id %}">Cancel</a>
    </form>

{% endblock %}

main_app/templates/main_app/item_form.html
{% extends 'base.html' %}

{% block content %}

    {% if object %}
        <h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
    {% else %}
        <h1>Add Item</h1>
    {% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn">
</form>

{% endblock %}

main_app/templates/main_app/store_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Store</h1>

  <h4>Are you sure you want to delete {{ object.name }}?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Delete" class="btn">
    <a href="{% url 'stores_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/store_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Store Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ store.name }}</span>
        <p>Location: {{ store.location }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'stores_update' store.id %}">Edit</a>
        <a href="{% url 'stores_delete' store.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/store_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Store</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/store_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Store List</h1>

{% for store in store_list %}
  <a href="{% url 'stores_details' store.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ store.name }}</span>
            <p>Location: {{ store.location }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}